//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.ServicioPermisos {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicioPermisos.IGenericoConsultaSCSWS")]
    public interface IGenericoConsultaSCSWS {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericoConsultaSCSWS/obtieneDatosGenericoSCS", ReplyAction="http://tempuri.org/IGenericoConsultaSCSWS/obtieneDatosGenericoSCSResponse")]
        string obtieneDatosGenericoSCS(int idConsulta, string parametros);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGenericoConsultaSCSWS/obtieneDatosGenericoSCS", ReplyAction="http://tempuri.org/IGenericoConsultaSCSWS/obtieneDatosGenericoSCSResponse")]
        System.Threading.Tasks.Task<string> obtieneDatosGenericoSCSAsync(int idConsulta, string parametros);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGenericoConsultaSCSWSChannel : ServiciosWeb.ServicioPermisos.IGenericoConsultaSCSWS, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GenericoConsultaSCSWSClient : System.ServiceModel.ClientBase<ServiciosWeb.ServicioPermisos.IGenericoConsultaSCSWS>, ServiciosWeb.ServicioPermisos.IGenericoConsultaSCSWS {
        
        public GenericoConsultaSCSWSClient() {
        }
        
        public GenericoConsultaSCSWSClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GenericoConsultaSCSWSClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenericoConsultaSCSWSClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GenericoConsultaSCSWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string obtieneDatosGenericoSCS(int idConsulta, string parametros) {
            return base.Channel.obtieneDatosGenericoSCS(idConsulta, parametros);
        }
        
        public System.Threading.Tasks.Task<string> obtieneDatosGenericoSCSAsync(int idConsulta, string parametros) {
            return base.Channel.obtieneDatosGenericoSCSAsync(idConsulta, parametros);
        }
    }
}
