//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.ConsultaRenapoWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://Renapo/", ConfigurationName="ConsultaRenapoWS.ConsultaRenapo")]
    public interface ConsultaRenapo {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento aCveCurp del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Renapo/ConsultaRenapo/consultarPorCurpRequest", ReplyAction="http://Renapo/ConsultaRenapo/consultarPorCurpResponse")]
        ServiciosWeb.ConsultaRenapoWS.consultarPorCurpResponse consultarPorCurp(ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Renapo/ConsultaRenapo/consultarPorCurpRequest", ReplyAction="http://Renapo/ConsultaRenapo/consultarPorCurpResponse")]
        System.Threading.Tasks.Task<ServiciosWeb.ConsultaRenapoWS.consultarPorCurpResponse> consultarPorCurpAsync(ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento aNombre del espacio de nombres  no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://Renapo/ConsultaRenapo/consultarCURPDetalleRequest", ReplyAction="http://Renapo/ConsultaRenapo/consultarCURPDetalleResponse")]
        ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleResponse consultarCURPDetalle(ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://Renapo/ConsultaRenapo/consultarCURPDetalleRequest", ReplyAction="http://Renapo/ConsultaRenapo/consultarCURPDetalleResponse")]
        System.Threading.Tasks.Task<ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleResponse> consultarCURPDetalleAsync(ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarPorCurpRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarPorCurp", Namespace="http://Renapo/", Order=0)]
        public ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequestBody Body;
        
        public consultarPorCurpRequest() {
        }
        
        public consultarPorCurpRequest(ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultarPorCurpRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aCveCurp;
        
        public consultarPorCurpRequestBody() {
        }
        
        public consultarPorCurpRequestBody(string aCveCurp) {
            this.aCveCurp = aCveCurp;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarPorCurpResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarPorCurpResponse", Namespace="http://Renapo/", Order=0)]
        public ServiciosWeb.ConsultaRenapoWS.consultarPorCurpResponseBody Body;
        
        public consultarPorCurpResponse() {
        }
        
        public consultarPorCurpResponse(ServiciosWeb.ConsultaRenapoWS.consultarPorCurpResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultarPorCurpResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public consultarPorCurpResponseBody() {
        }
        
        public consultarPorCurpResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarCURPDetalleRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarCURPDetalle", Namespace="http://Renapo/", Order=0)]
        public ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequestBody Body;
        
        public consultarCURPDetalleRequest() {
        }
        
        public consultarCURPDetalleRequest(ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultarCURPDetalleRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string aNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string aPrimerApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string aSegundoApellido;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string aFechaNacimiento;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string aCveAlfaEntFedNac;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string aSexo;
        
        public consultarCURPDetalleRequestBody() {
        }
        
        public consultarCURPDetalleRequestBody(string aNombre, string aPrimerApellido, string aSegundoApellido, string aFechaNacimiento, string aCveAlfaEntFedNac, string aSexo) {
            this.aNombre = aNombre;
            this.aPrimerApellido = aPrimerApellido;
            this.aSegundoApellido = aSegundoApellido;
            this.aFechaNacimiento = aFechaNacimiento;
            this.aCveAlfaEntFedNac = aCveAlfaEntFedNac;
            this.aSexo = aSexo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultarCURPDetalleResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="consultarCURPDetalleResponse", Namespace="http://Renapo/", Order=0)]
        public ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleResponseBody Body;
        
        public consultarCURPDetalleResponse() {
        }
        
        public consultarCURPDetalleResponse(ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="")]
    public partial class consultarCURPDetalleResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string @return;
        
        public consultarCURPDetalleResponseBody() {
        }
        
        public consultarCURPDetalleResponseBody(string @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ConsultaRenapoChannel : ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ConsultaRenapoClient : System.ServiceModel.ClientBase<ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo>, ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo {
        
        public ConsultaRenapoClient() {
        }
        
        public ConsultaRenapoClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ConsultaRenapoClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaRenapoClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ConsultaRenapoClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.ConsultaRenapoWS.consultarPorCurpResponse ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo.consultarPorCurp(ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequest request) {
            return base.Channel.consultarPorCurp(request);
        }
        
        public string consultarPorCurp(string aCveCurp) {
            ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequest inValue = new ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequest();
            inValue.Body = new ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequestBody();
            inValue.Body.aCveCurp = aCveCurp;
            ServiciosWeb.ConsultaRenapoWS.consultarPorCurpResponse retVal = ((ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo)(this)).consultarPorCurp(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.ConsultaRenapoWS.consultarPorCurpResponse> ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo.consultarPorCurpAsync(ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequest request) {
            return base.Channel.consultarPorCurpAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.ConsultaRenapoWS.consultarPorCurpResponse> consultarPorCurpAsync(string aCveCurp) {
            ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequest inValue = new ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequest();
            inValue.Body = new ServiciosWeb.ConsultaRenapoWS.consultarPorCurpRequestBody();
            inValue.Body.aCveCurp = aCveCurp;
            return ((ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo)(this)).consultarPorCurpAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleResponse ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo.consultarCURPDetalle(ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequest request) {
            return base.Channel.consultarCURPDetalle(request);
        }
        
        public string consultarCURPDetalle(string aNombre, string aPrimerApellido, string aSegundoApellido, string aFechaNacimiento, string aCveAlfaEntFedNac, string aSexo) {
            ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequest inValue = new ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequest();
            inValue.Body = new ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequestBody();
            inValue.Body.aNombre = aNombre;
            inValue.Body.aPrimerApellido = aPrimerApellido;
            inValue.Body.aSegundoApellido = aSegundoApellido;
            inValue.Body.aFechaNacimiento = aFechaNacimiento;
            inValue.Body.aCveAlfaEntFedNac = aCveAlfaEntFedNac;
            inValue.Body.aSexo = aSexo;
            ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleResponse retVal = ((ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo)(this)).consultarCURPDetalle(inValue);
            return retVal.Body.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleResponse> ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo.consultarCURPDetalleAsync(ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequest request) {
            return base.Channel.consultarCURPDetalleAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleResponse> consultarCURPDetalleAsync(string aNombre, string aPrimerApellido, string aSegundoApellido, string aFechaNacimiento, string aCveAlfaEntFedNac, string aSexo) {
            ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequest inValue = new ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequest();
            inValue.Body = new ServiciosWeb.ConsultaRenapoWS.consultarCURPDetalleRequestBody();
            inValue.Body.aNombre = aNombre;
            inValue.Body.aPrimerApellido = aPrimerApellido;
            inValue.Body.aSegundoApellido = aSegundoApellido;
            inValue.Body.aFechaNacimiento = aFechaNacimiento;
            inValue.Body.aCveAlfaEntFedNac = aCveAlfaEntFedNac;
            inValue.Body.aSexo = aSexo;
            return ((ServiciosWeb.ConsultaRenapoWS.ConsultaRenapo)(this)).consultarCURPDetalleAsync(inValue);
        }
    }
}
