//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.CertificadoMediaSuperiorWS {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", ConfigurationName="CertificadoMediaSuperiorWS.CertificadosIEMSPortType")]
    public interface CertificadosIEMSPortType {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación cargaCertificadosIEMS no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSResponse1 cargaCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSResponse1> cargaCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación consultaCertificadosIEMS no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSResponse1 consultaCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSResponse1> consultaCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación descargaCertificadosIEMS no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSResponse1 descargaCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSResponse1> descargaCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest1 request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que la operación cancelarCertificadosIEMS no es RPC ni está encapsulada en un documento.
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSResponse1 cancelarCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest1 request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSResponse1> cancelarCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest1 request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cargaCertificadosIEMSRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string nombreArchivoField;
        
        private byte[] archivoBase64Field;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string nombreArchivo {
            get {
                return this.nombreArchivoField;
            }
            set {
                this.nombreArchivoField = value;
                this.RaisePropertyChanged("nombreArchivo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=1)]
        public byte[] archivoBase64 {
            get {
                return this.archivoBase64Field;
            }
            set {
                this.archivoBase64Field = value;
                this.RaisePropertyChanged("archivoBase64");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class autenticacionType : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string usuarioField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
                this.RaisePropertyChanged("usuario");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                this.passwordField = value;
                this.RaisePropertyChanged("password");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cargaCertificadosIEMSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargaCertificadosIEMSRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest cargaCertificadosIEMSRequest;
        
        public cargaCertificadosIEMSRequest1() {
        }
        
        public cargaCertificadosIEMSRequest1(ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest cargaCertificadosIEMSRequest) {
            this.cargaCertificadosIEMSRequest = cargaCertificadosIEMSRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cargaCertificadosIEMSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSResponse cargaCertificadosIEMSResponse;
        
        public cargaCertificadosIEMSResponse1() {
        }
        
        public cargaCertificadosIEMSResponse1(ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSResponse cargaCertificadosIEMSResponse) {
            this.cargaCertificadosIEMSResponse = cargaCertificadosIEMSResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class consultaCertificadosIEMSRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class consultaCertificadosIEMSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private short estatusLoteField;
        
        private string mensajeField;
        
        private byte[] excelBase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public short estatusLote {
            get {
                return this.estatusLoteField;
            }
            set {
                this.estatusLoteField = value;
                this.RaisePropertyChanged("estatusLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=3)]
        public byte[] excelBase64 {
            get {
                return this.excelBase64Field;
            }
            set {
                this.excelBase64Field = value;
                this.RaisePropertyChanged("excelBase64");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCertificadosIEMSRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest consultaCertificadosIEMSRequest;
        
        public consultaCertificadosIEMSRequest1() {
        }
        
        public consultaCertificadosIEMSRequest1(ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest consultaCertificadosIEMSRequest) {
            this.consultaCertificadosIEMSRequest = consultaCertificadosIEMSRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class consultaCertificadosIEMSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSResponse consultaCertificadosIEMSResponse;
        
        public consultaCertificadosIEMSResponse1() {
        }
        
        public consultaCertificadosIEMSResponse1(ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSResponse consultaCertificadosIEMSResponse) {
            this.consultaCertificadosIEMSResponse = consultaCertificadosIEMSResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class descargaCertificadosIEMSRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class descargaCertificadosIEMSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string numeroLoteField;
        
        private string mensajeField;
        
        private byte[] certificadosBase64Field;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer", Order=0)]
        public string numeroLote {
            get {
                return this.numeroLoteField;
            }
            set {
                this.numeroLoteField = value;
                this.RaisePropertyChanged("numeroLote");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="base64Binary", Order=2)]
        public byte[] certificadosBase64 {
            get {
                return this.certificadosBase64Field;
            }
            set {
                this.certificadosBase64Field = value;
                this.RaisePropertyChanged("certificadosBase64");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargaCertificadosIEMSRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest descargaCertificadosIEMSRequest;
        
        public descargaCertificadosIEMSRequest1() {
        }
        
        public descargaCertificadosIEMSRequest1(ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest descargaCertificadosIEMSRequest) {
            this.descargaCertificadosIEMSRequest = descargaCertificadosIEMSRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class descargaCertificadosIEMSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSResponse descargaCertificadosIEMSResponse;
        
        public descargaCertificadosIEMSResponse1() {
        }
        
        public descargaCertificadosIEMSResponse1(ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSResponse descargaCertificadosIEMSResponse) {
            this.descargaCertificadosIEMSResponse = descargaCertificadosIEMSResponse;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cancelarCertificadosIEMSRequest : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string folioCertificadoField;
        
        private autenticacionType autenticacionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string folioCertificado {
            get {
                return this.folioCertificadoField;
            }
            set {
                this.folioCertificadoField = value;
                this.RaisePropertyChanged("folioCertificado");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public autenticacionType autenticacion {
            get {
                return this.autenticacionField;
            }
            set {
                this.autenticacionField = value;
                this.RaisePropertyChanged("autenticacion");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://ws.web.mec.sep.mx/schemas")]
    public partial class cancelarCertificadosIEMSResponse : object, System.ComponentModel.INotifyPropertyChanged {
        
        private int codigoField;
        
        private string mensajeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public int codigo {
            get {
                return this.codigoField;
            }
            set {
                this.codigoField = value;
                this.RaisePropertyChanged("codigo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string mensaje {
            get {
                return this.mensajeField;
            }
            set {
                this.mensajeField = value;
                this.RaisePropertyChanged("mensaje");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarCertificadosIEMSRequest1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest cancelarCertificadosIEMSRequest;
        
        public cancelarCertificadosIEMSRequest1() {
        }
        
        public cancelarCertificadosIEMSRequest1(ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest cancelarCertificadosIEMSRequest) {
            this.cancelarCertificadosIEMSRequest = cancelarCertificadosIEMSRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class cancelarCertificadosIEMSResponse1 {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.web.mec.sep.mx/schemas", Order=0)]
        public ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSResponse cancelarCertificadosIEMSResponse;
        
        public cancelarCertificadosIEMSResponse1() {
        }
        
        public cancelarCertificadosIEMSResponse1(ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSResponse cancelarCertificadosIEMSResponse) {
            this.cancelarCertificadosIEMSResponse = cancelarCertificadosIEMSResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CertificadosIEMSPortTypeChannel : ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CertificadosIEMSPortTypeClient : System.ServiceModel.ClientBase<ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType>, ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType {
        
        public CertificadosIEMSPortTypeClient() {
        }
        
        public CertificadosIEMSPortTypeClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CertificadosIEMSPortTypeClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificadosIEMSPortTypeClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CertificadosIEMSPortTypeClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSResponse1 ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType.cargaCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest1 request) {
            return base.Channel.cargaCertificadosIEMS(request);
        }
        
        public ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSResponse cargaCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest cargaCertificadosIEMSRequest) {
            ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest1 inValue = new ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest1();
            inValue.cargaCertificadosIEMSRequest = cargaCertificadosIEMSRequest;
            ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSResponse1 retVal = ((ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType)(this)).cargaCertificadosIEMS(inValue);
            return retVal.cargaCertificadosIEMSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSResponse1> ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType.cargaCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest1 request) {
            return base.Channel.cargaCertificadosIEMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSResponse1> cargaCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest cargaCertificadosIEMSRequest) {
            ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest1 inValue = new ServiciosWeb.CertificadoMediaSuperiorWS.cargaCertificadosIEMSRequest1();
            inValue.cargaCertificadosIEMSRequest = cargaCertificadosIEMSRequest;
            return ((ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType)(this)).cargaCertificadosIEMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSResponse1 ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType.consultaCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest1 request) {
            return base.Channel.consultaCertificadosIEMS(request);
        }
        
        public ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSResponse consultaCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest consultaCertificadosIEMSRequest) {
            ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest1 inValue = new ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest1();
            inValue.consultaCertificadosIEMSRequest = consultaCertificadosIEMSRequest;
            ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSResponse1 retVal = ((ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType)(this)).consultaCertificadosIEMS(inValue);
            return retVal.consultaCertificadosIEMSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSResponse1> ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType.consultaCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest1 request) {
            return base.Channel.consultaCertificadosIEMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSResponse1> consultaCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest consultaCertificadosIEMSRequest) {
            ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest1 inValue = new ServiciosWeb.CertificadoMediaSuperiorWS.consultaCertificadosIEMSRequest1();
            inValue.consultaCertificadosIEMSRequest = consultaCertificadosIEMSRequest;
            return ((ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType)(this)).consultaCertificadosIEMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSResponse1 ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType.descargaCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest1 request) {
            return base.Channel.descargaCertificadosIEMS(request);
        }
        
        public ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSResponse descargaCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest descargaCertificadosIEMSRequest) {
            ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest1 inValue = new ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest1();
            inValue.descargaCertificadosIEMSRequest = descargaCertificadosIEMSRequest;
            ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSResponse1 retVal = ((ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType)(this)).descargaCertificadosIEMS(inValue);
            return retVal.descargaCertificadosIEMSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSResponse1> ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType.descargaCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest1 request) {
            return base.Channel.descargaCertificadosIEMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSResponse1> descargaCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest descargaCertificadosIEMSRequest) {
            ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest1 inValue = new ServiciosWeb.CertificadoMediaSuperiorWS.descargaCertificadosIEMSRequest1();
            inValue.descargaCertificadosIEMSRequest = descargaCertificadosIEMSRequest;
            return ((ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType)(this)).descargaCertificadosIEMSAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSResponse1 ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType.cancelarCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest1 request) {
            return base.Channel.cancelarCertificadosIEMS(request);
        }
        
        public ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSResponse cancelarCertificadosIEMS(ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest cancelarCertificadosIEMSRequest) {
            ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest1 inValue = new ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest1();
            inValue.cancelarCertificadosIEMSRequest = cancelarCertificadosIEMSRequest;
            ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSResponse1 retVal = ((ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType)(this)).cancelarCertificadosIEMS(inValue);
            return retVal.cancelarCertificadosIEMSResponse;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSResponse1> ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType.cancelarCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest1 request) {
            return base.Channel.cancelarCertificadosIEMSAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSResponse1> cancelarCertificadosIEMSAsync(ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest cancelarCertificadosIEMSRequest) {
            ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest1 inValue = new ServiciosWeb.CertificadoMediaSuperiorWS.cancelarCertificadosIEMSRequest1();
            inValue.cancelarCertificadosIEMSRequest = cancelarCertificadosIEMSRequest;
            return ((ServiciosWeb.CertificadoMediaSuperiorWS.CertificadosIEMSPortType)(this)).cancelarCertificadosIEMSAsync(inValue);
        }
    }
}
