//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerAreaConocimiento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cerAreaConocimiento()
        {
            this.cerDocumento = new HashSet<cerDocumento>();
            this.cerRelPlanPeriodoAreaConocimientoMateria = new HashSet<cerRelPlanPeriodoAreaConocimientoMateria>();
        }
    
        public string idAreaConocimiento { get; set; }
        public string areaConocimientoDescripcion { get; set; }
        public string areaEgresoCompetenciasTrayecto { get; set; }
        public string areaTotalCreditos { get; set; }
        public string areaEgresoCompetenciasTrayectoNoAcreditado { get; set; }
        public string insId { get; set; }
        public string areaEgresoCompetenciasTrayectoAcreditado { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerDocumento> cerDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerRelPlanPeriodoAreaConocimientoMateria> cerRelPlanPeriodoAreaConocimientoMateria { get; set; }
    }
}
