//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerBitacora
    {
        public string bitId { get; set; }
        public Nullable<System.DateTime> bitFecha { get; set; }
        public string bitUsuario { get; set; }
        public string bitDescripcion { get; set; }
        public Nullable<bool> bitExitoso { get; set; }
        public string accId { get; set; }
    
        public virtual cerCatAccion cerCatAccion { get; set; }
    }
}
