//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerCatFirmante
    {
        public string firCurp { get; set; }
        public string firNombre { get; set; }
        public string firPrimerApellido { get; set; }
        public string firSegundoApellido { get; set; }
        public string firIdCargo { get; set; }
        public string firCargo { get; set; }
        public string firCertificadoPublico { get; set; }
        public string firNumeroCertificado { get; set; }
        public string firCorreo { get; set; }
        public bool firPredeterminado { get; set; }
        public string insId { get; set; }
        public string firId { get; set; }
        public Nullable<System.DateTime> firVigenciaCertificado { get; set; }
    
        public virtual cerConfiguracionInstitucion cerConfiguracionInstitucion { get; set; }
    }
}
