//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerCatEstatusDocumento
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cerCatEstatusDocumento()
        {
            this.cerDocumento = new HashSet<cerDocumento>();
        }
    
        public int estDocumentoId { get; set; }
        public string estDocumentoDescripcion { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerDocumento> cerDocumento { get; set; }
    }
}
