//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerCompetenciasPlan
    {
        public int idCompetencia { get; set; }
        public string competenciaDescripcion { get; set; }
        public string idPlan { get; set; }
        public Nullable<int> competenciaOrden { get; set; }
    
        public virtual cerCatPlan cerCatPlan { get; set; }
    }
}
