//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerConfiguracionInstitucion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cerConfiguracionInstitucion()
        {
            this.cerCatFirmante = new HashSet<cerCatFirmante>();
            this.cerCatPlantilla = new HashSet<cerCatPlantilla>();
            this.cerCatTipoUAC = new HashSet<cerCatTipoUAC>();
            this.cerDocumento = new HashSet<cerDocumento>();
            this.cerParametroValor = new HashSet<cerParametroValor>();
            this.cerRelPlanPeriodoAreaConocimientoMateria = new HashSet<cerRelPlanPeriodoAreaConocimientoMateria>();
            this.cerSolicitud = new HashSet<cerSolicitud>();
        }
    
        public string insId { get; set; }
        public string InsNombre { get; set; }
        public string insUsuarioWS { get; set; }
        public string insContrasenaWS { get; set; }
        public Nullable<bool> insNotificacionProfesionista { get; set; }
        public string insTokenSeguridadDescarga { get; set; }
        public Nullable<bool> insCertificadosPublicos { get; set; }
        public string insBotonMenu { get; set; }
        public string insBotonSalir { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerCatFirmante> cerCatFirmante { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerCatPlantilla> cerCatPlantilla { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerCatTipoUAC> cerCatTipoUAC { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerDocumento> cerDocumento { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerParametroValor> cerParametroValor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerRelPlanPeriodoAreaConocimientoMateria> cerRelPlanPeriodoAreaConocimientoMateria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerSolicitud> cerSolicitud { get; set; }
    }
}
