//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerCompetenciasIEMS
    {
        public string CompetenciasIEMSnombreProfesional { get; set; }
        public string docId { get; set; }
        public Nullable<int> CompetenciasIEMSorden { get; set; }
    
        public virtual cerDocumento cerDocumento { get; set; }
    }
}
