//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerCatPlan
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cerCatPlan()
        {
            this.cerCatMateria = new HashSet<cerCatMateria>();
            this.cerCompetenciasPlan = new HashSet<cerCompetenciasPlan>();
            this.cerRelPlanPeriodoAreaConocimientoMateria = new HashSet<cerRelPlanPeriodoAreaConocimientoMateria>();
        }
    
        public string idPlan { get; set; }
        public string planDescripcion { get; set; }
        public string planEgresoCompetenciasIdCampoDisciplinar { get; set; }
        public string planEgresoCompetenciasCampoDisciplinar { get; set; }
        public string planEgresoCompetenciasTipoPerfilProfesionalIEMS { get; set; }
        public string planEgresoCompetenciasNombrePerfilProfesionalIEMS { get; set; }
        public string planPlantelClaveRvoe { get; set; }
        public string acreditacionIdTipoEstudiosIEMS { get; set; }
        public string acreditacionTipoEstudiosIEMS { get; set; }
        public string acreditacionTipoPerfilProfesionalIEMS { get; set; }
        public string acreditacionClavePlanEstudios { get; set; }
        public string acreditacionNombreTipoPerfilProfesionalIEMS { get; set; }
        public string uacIdTipoPeriodo { get; set; }
        public string uacNombreTipoPeriodo { get; set; }
        public string servicioIdOpcionEducativa { get; set; }
        public string servicioOpcionEducativa { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerCatMateria> cerCatMateria { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerCompetenciasPlan> cerCompetenciasPlan { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cerRelPlanPeriodoAreaConocimientoMateria> cerRelPlanPeriodoAreaConocimientoMateria { get; set; }
    }
}
