//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerCompetenciaDocumento
    {
        public string idMateria { get; set; }
        public string docId { get; set; }
        public string competenciaNombre { get; set; }
        public string competenciaCalificacion { get; set; }
        public string competenciaDictamen { get; set; }
        public string competenciaTotalHorasUAC { get; set; }
        public string competenciaCreditos { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> idPeriodo { get; set; }
    
        public virtual cerDocumento cerDocumento { get; set; }
    }
}
