//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerDocumento_Tem
    {
        public Nullable<int> fila { get; set; }
        public string docId { get; set; }
        public string carId { get; set; }
        public string docPlanId { get; set; }
        public string idAreaConocimiento { get; set; }
        public string docDecVersion { get; set; }
        public string docDecTipocertificado { get; set; }
        public string docDecFolioControl { get; set; }
        public string docFirmaResponsableNombre { get; set; }
        public string docFirmaResponsablePrimerApellido { get; set; }
        public string docFirmaResponsableSegundoApellido { get; set; }
        public string docFirmaResponsableCurp { get; set; }
        public string docFirmaResponsableIdCargo { get; set; }
        public string docFirmaResponsableCargo { get; set; }
        public string docFirmaResponsableCertificadoResponsable { get; set; }
        public string docfirmaResponsableNoCertificadoResponsable { get; set; }
        public string docServicioNombreTipoDependencia { get; set; }
        public string docServicioIdIEMS { get; set; }
        public string docServicioNombreIEMS { get; set; }
        public string docServicioIdOpcionEducativa { get; set; }
        public string docServicioOpcionEducativa { get; set; }
        public Nullable<int> docPlantelIdTipoPlantel { get; set; }
        public string docPlantelTipoPlantel { get; set; }
        public string docPlantelNombreNumeroPlantel { get; set; }
        public string docPlantelIdLocalidad { get; set; }
        public string docPlantelLocalidad { get; set; }
        public string docPlantelIdEntidadFederativa { get; set; }
        public string docPlantelEntidadFederativa { get; set; }
        public string docPlantelCCT { get; set; }
        public string docPlantelClaveRvoe { get; set; }
        public string docplantelIdGeneroPlantel { get; set; }
        public string docPlantelGeneroPlantel { get; set; }
        public string docPlantelIdSostenimiento { get; set; }
        public string docPlantelSostenimiento { get; set; }
        public string docAlumnoNombre { get; set; }
        public string docAlumnoNombreRENAPO { get; set; }
        public string docAlumnoPrimerApellido { get; set; }
        public string docAlumnoPrimerApellidoRENAPO { get; set; }
        public string docAlumnoSegundoApellido { get; set; }
        public string docAlumnoSegundoApellidoRENAPO { get; set; }
        public string docAlumnoCurp { get; set; }
        public string docAlumnoCurpRENAPO { get; set; }
        public string docAlumnoNumeroControl { get; set; }
        public string docAcreditacionIdTipoEstudiosIEMS { get; set; }
        public string docAcreditacionTipoEstudiosIEMS { get; set; }
        public string docAcreditacionTipoPerfilProfesionalIEMS { get; set; }
        public string docAcreditacionNombreTipoPerfilProfesionalIEMS { get; set; }
        public string docAcreditacionPeriodoInicio { get; set; }
        public string docAcreditacionPeriodoTermino { get; set; }
        public string docAcreditacionCreditosObtenidos { get; set; }
        public string docAcreditacionTotalCreditos { get; set; }
        public string docAcreditacionPromedioAprovechamiento { get; set; }
        public string docAcreditacionPromedioAprovechamientoTexto { get; set; }
        public string docCompetencias { get; set; }
        public string docEgresoCompetenciasTrayecto { get; set; }
        public string docEgresoCompetenciasIdCampoDisciplinar { get; set; }
        public string docEgresoCompetenciasCampoDisciplinar { get; set; }
        public string docEgresoCompetenciasTipoPerfilProfesionalIEMS { get; set; }
        public string docEgresoCompetenciasNombrePerfilProfesionalIEMS { get; set; }
        public string docCompetenciasIEMS { get; set; }
        public string docCorreo { get; set; }
        public string docObservaciones { get; set; }
        public string docAcreditacionClavePlanEstudios { get; set; }
        public string insId { get; set; }
        public Nullable<int> totalErrores { get; set; }
        public Nullable<int> totalObservaciones { get; set; }
        public string planId { get; set; }
        public Nullable<bool> docInsertado { get; set; }
        public string docUACSidTipoPeriodo { get; set; }
        public string docUACSnombreTipoPeriodo { get; set; }
        public string docServicioIemsNombreSEN { get; set; }
        public string docServicioIemsnombreIEMSparticular { get; set; }
        public string docServicioIemsInstitucionRVOE { get; set; }
        public string docServicioIemsIdTipoIEMS { get; set; }
        public string docServicioIemsTipoIEMS { get; set; }
        public Nullable<System.DateTime> docPlantelOServicioEducativoFechaInicioRVOE { get; set; }
        public string docAcreditacionidNivelEstudios { get; set; }
        public string docAcreditacionNivelEstudios { get; set; }
    }
}
