//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerParametroValor
    {
        public string parId { get; set; }
        public string insId { get; set; }
        public string parValor { get; set; }
        public string parDescripcion { get; set; }
        public string docTipoId { get; set; }
        public bool parValorRequerido { get; set; }
    
        public virtual cerCatTipoDocumento cerCatTipoDocumento { get; set; }
        public virtual cerConfiguracionInstitucion cerConfiguracionInstitucion { get; set; }
    }
}
