//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerRelPlanPeriodoAreaConocimientoMateria
    {
        public int idPeriodo { get; set; }
        public string idPlan { get; set; }
        public string idMateria { get; set; }
        public string insId { get; set; }
        public int orden { get; set; }
        public string idAreaConocimiento { get; set; }
        public string docTipoId { get; set; }
        public Nullable<bool> condicionaTrayecto { get; set; }
    
        public virtual cerAreaConocimiento cerAreaConocimiento { get; set; }
        public virtual cerCatMateria cerCatMateria { get; set; }
        public virtual cerCatPeriodo cerCatPeriodo { get; set; }
        public virtual cerCatPlan cerCatPlan { get; set; }
        public virtual cerCatTipoDocumento cerCatTipoDocumento { get; set; }
        public virtual cerConfiguracionInstitucion cerConfiguracionInstitucion { get; set; }
    }
}
