//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerTokenDescarga
    {
        public string tokCodigo { get; set; }
        public System.DateTime tokfechaCreacion { get; set; }
        public Nullable<System.DateTime> tokfechaDescarga { get; set; }
        public bool tokEstatus { get; set; }
        public bool tokUsado { get; set; }
        public string tokCURP { get; set; }
    }
}
