//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CertificadosMediaSuperiorEntities : DbContext
    {
        public CertificadosMediaSuperiorEntities()
            : base("name=CertificadosMediaSuperiorEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cerAreaConocimiento> cerAreaConocimiento { get; set; }
        public virtual DbSet<cerBitacora> cerBitacora { get; set; }
        public virtual DbSet<cerCarga> cerCarga { get; set; }
        public virtual DbSet<cerCatAccion> cerCatAccion { get; set; }
        public virtual DbSet<cerCatEstatusDocumento> cerCatEstatusDocumento { get; set; }
        public virtual DbSet<cerCatEstatusSolicitud> cerCatEstatusSolicitud { get; set; }
        public virtual DbSet<cerCatFirmante> cerCatFirmante { get; set; }
        public virtual DbSet<cerCatMateria> cerCatMateria { get; set; }
        public virtual DbSet<cerCatPeriodo> cerCatPeriodo { get; set; }
        public virtual DbSet<cerCatPlan> cerCatPlan { get; set; }
        public virtual DbSet<cerCatPlantilla> cerCatPlantilla { get; set; }
        public virtual DbSet<cerCatTipoDocumento> cerCatTipoDocumento { get; set; }
        public virtual DbSet<cerCatTipoUAC> cerCatTipoUAC { get; set; }
        public virtual DbSet<cerCompetenciaDocumento> cerCompetenciaDocumento { get; set; }
        public virtual DbSet<cerCompetenciasIEMS> cerCompetenciasIEMS { get; set; }
        public virtual DbSet<cerCompetenciasPlan> cerCompetenciasPlan { get; set; }
        public virtual DbSet<cerConfiguracionInstitucion> cerConfiguracionInstitucion { get; set; }
        public virtual DbSet<cerDocumento> cerDocumento { get; set; }
        public virtual DbSet<cerDocumento_Tem> cerDocumento_Tem { get; set; }
        public virtual DbSet<cerParametroValor> cerParametroValor { get; set; }
        public virtual DbSet<cerRelPlanPeriodoAreaConocimientoMateria> cerRelPlanPeriodoAreaConocimientoMateria { get; set; }
        public virtual DbSet<cerSolicitud> cerSolicitud { get; set; }
        public virtual DbSet<cerTokenDescarga> cerTokenDescarga { get; set; }
        public virtual DbSet<cerUACDocumento> cerUACDocumento { get; set; }
        public virtual DbSet<ViewCerDocumento> ViewCerDocumento { get; set; }
        public virtual DbSet<ViewPlantillas> ViewPlantillas { get; set; }
        public virtual DbSet<ViewSolicitud> ViewSolicitud { get; set; }
        public virtual DbSet<VWGridSellado> VWGridSellado { get; set; }
    }
}
