//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class cerUACDocumento
    {
        public string idMateria { get; set; }
        public string docId { get; set; }
        public string UACcct { get; set; }
        public string UACidTipo { get; set; }
        public string UACtipo { get; set; }
        public string UACnombre { get; set; }
        public string UACcalificacion { get; set; }
        public string UACdictamen { get; set; }
        public string UACtotalHorasUAC { get; set; }
        public string UACcreditos { get; set; }
        public string UACperiodoEscolar { get; set; }
        public string UACnumeroPeriodo { get; set; }
        public Nullable<int> orden { get; set; }
        public Nullable<int> idPeriodo { get; set; }
    
        public virtual cerDocumento cerDocumento { get; set; }
    }
}
