//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewPlantillas
    {
        public string planId { get; set; }
        public string planNombre { get; set; }
        public Nullable<int> planNumHojas { get; set; }
        public Nullable<bool> planEstatus { get; set; }
        public string insId { get; set; }
        public string idPlan { get; set; }
        public string planDescripcion { get; set; }
        public string docTipoId { get; set; }
        public string tdDescripcion { get; set; }
        public Nullable<int> registros { get; set; }
    }
}
