//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class ViewCerDocumento
    {
        public string docId { get; set; }
        public Nullable<int> estDocumentoId { get; set; }
        public string docAlumnoNombre { get; set; }
        public string docAlumnoPrimerApellido { get; set; }
        public string docAlumnoSegundoApellido { get; set; }
        public string docAlumnoCurp { get; set; }
        public string Institucion { get; set; }
        public string docCorreo { get; set; }
        public string solId { get; set; }
        public string docPlanId { get; set; }
        public string PlanEstudios { get; set; }
        public string docTipoId { get; set; }
        public string docDecFolioControl { get; set; }
        public string insId { get; set; }
        public string planId { get; set; }
        public string docMensajeResultado { get; set; }
        public string TipoCertificado { get; set; }
        public string docAlumnoNumeroControl { get; set; }
    }
}
