//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BusinessModel.Persistence.CertificadosElectronicosMS
{
    using System;
    using System.Collections.Generic;
    
    public partial class VWGridSellado
    {
        public string docId { get; set; }
        public string insId { get; set; }
        public string docTipoId { get; set; }
        public string docPlanId { get; set; }
        public string docAreaEspecializacion { get; set; }
        public int estDocumentoId { get; set; }
        public string estatusDescripcion { get; set; }
        public string docAlumnoNombre { get; set; }
        public string docAlumnoPrimerApellido { get; set; }
        public string docAlumnoSegundoApellido { get; set; }
        public string docAlumnoCurp { get; set; }
        public string docAlumnoNumeroControl { get; set; }
        public Nullable<System.DateTime> docFechaRegistro { get; set; }
        public string areaConocimientoDescripcion { get; set; }
        public string planDescripcion { get; set; }
        public string docDescripcion { get; set; }
    }
}
