//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace ServiciosWeb.SesionWS {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="BasicHttpBinding_ISesionWSService", Namespace="http://tempuri.org/")]
    public partial class SesionWSService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback getSesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSesionDinamicaOperationCompleted;
        
        private System.Threading.SendOrPostCallback getCerrarSesionOperationCompleted;
        
        private System.Threading.SendOrPostCallback getSesionStringOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public SesionWSService() {
            this.Url = global::ServiciosWeb.Properties.Settings.Default.ServiciosWeb_SesionWS_SesionWSService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event getSesionCompletedEventHandler getSesionCompleted;
        
        /// <remarks/>
        public event getSesionDinamicaCompletedEventHandler getSesionDinamicaCompleted;
        
        /// <remarks/>
        public event getCerrarSesionCompletedEventHandler getCerrarSesionCompleted;
        
        /// <remarks/>
        public event getSesionStringCompletedEventHandler getSesionStringCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISesionWSService/getSesion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SesionImpl getSesion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idSesion, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idAplicacion) {
            object[] results = this.Invoke("getSesion", new object[] {
                        idSesion,
                        idAplicacion});
            return ((SesionImpl)(results[0]));
        }
        
        /// <remarks/>
        public void getSesionAsync(string idSesion, string idAplicacion) {
            this.getSesionAsync(idSesion, idAplicacion, null);
        }
        
        /// <remarks/>
        public void getSesionAsync(string idSesion, string idAplicacion, object userState) {
            if ((this.getSesionOperationCompleted == null)) {
                this.getSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSesionOperationCompleted);
            }
            this.InvokeAsync("getSesion", new object[] {
                        idSesion,
                        idAplicacion}, this.getSesionOperationCompleted, userState);
        }
        
        private void OngetSesionOperationCompleted(object arg) {
            if ((this.getSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSesionCompleted(this, new getSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISesionWSService/getSesionDinamica", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public sesionMensajesImpl getSesionDinamica([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idSesion, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idAplicacion) {
            object[] results = this.Invoke("getSesionDinamica", new object[] {
                        idSesion,
                        idAplicacion});
            return ((sesionMensajesImpl)(results[0]));
        }
        
        /// <remarks/>
        public void getSesionDinamicaAsync(string idSesion, string idAplicacion) {
            this.getSesionDinamicaAsync(idSesion, idAplicacion, null);
        }
        
        /// <remarks/>
        public void getSesionDinamicaAsync(string idSesion, string idAplicacion, object userState) {
            if ((this.getSesionDinamicaOperationCompleted == null)) {
                this.getSesionDinamicaOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSesionDinamicaOperationCompleted);
            }
            this.InvokeAsync("getSesionDinamica", new object[] {
                        idSesion,
                        idAplicacion}, this.getSesionDinamicaOperationCompleted, userState);
        }
        
        private void OngetSesionDinamicaOperationCompleted(object arg) {
            if ((this.getSesionDinamicaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSesionDinamicaCompleted(this, new getSesionDinamicaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISesionWSService/getCerrarSesion", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SesionImpl getCerrarSesion([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string sesGuid) {
            object[] results = this.Invoke("getCerrarSesion", new object[] {
                        sesGuid});
            return ((SesionImpl)(results[0]));
        }
        
        /// <remarks/>
        public void getCerrarSesionAsync(string sesGuid) {
            this.getCerrarSesionAsync(sesGuid, null);
        }
        
        /// <remarks/>
        public void getCerrarSesionAsync(string sesGuid, object userState) {
            if ((this.getCerrarSesionOperationCompleted == null)) {
                this.getCerrarSesionOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetCerrarSesionOperationCompleted);
            }
            this.InvokeAsync("getCerrarSesion", new object[] {
                        sesGuid}, this.getCerrarSesionOperationCompleted, userState);
        }
        
        private void OngetCerrarSesionOperationCompleted(object arg) {
            if ((this.getCerrarSesionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getCerrarSesionCompleted(this, new getCerrarSesionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri.org/ISesionWSService/getSesionString", RequestNamespace="http://tempuri.org/", ResponseNamespace="http://tempuri.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SesionStringImpl getSesionString([System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idSesion, [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)] string idAplicacion) {
            object[] results = this.Invoke("getSesionString", new object[] {
                        idSesion,
                        idAplicacion});
            return ((SesionStringImpl)(results[0]));
        }
        
        /// <remarks/>
        public void getSesionStringAsync(string idSesion, string idAplicacion) {
            this.getSesionStringAsync(idSesion, idAplicacion, null);
        }
        
        /// <remarks/>
        public void getSesionStringAsync(string idSesion, string idAplicacion, object userState) {
            if ((this.getSesionStringOperationCompleted == null)) {
                this.getSesionStringOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetSesionStringOperationCompleted);
            }
            this.InvokeAsync("getSesionString", new object[] {
                        idSesion,
                        idAplicacion}, this.getSesionStringOperationCompleted, userState);
        }
        
        private void OngetSesionStringOperationCompleted(object arg) {
            if ((this.getSesionStringCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getSesionStringCompleted(this, new getSesionStringCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS")]
    public partial class SesionImpl {
        
        private accionSesion[] arbolAccionesField;
        
        private int idStatusField;
        
        private bool idStatusFieldSpecified;
        
        private rolSesion[] rolesField;
        
        private Sesion sesionField;
        
        private string statusField;
        
        private UsuarioSesion usuarioSesionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public accionSesion[] arbolAcciones {
            get {
                return this.arbolAccionesField;
            }
            set {
                this.arbolAccionesField = value;
            }
        }
        
        /// <remarks/>
        public int idStatus {
            get {
                return this.idStatusField;
            }
            set {
                this.idStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idStatusSpecified {
            get {
                return this.idStatusFieldSpecified;
            }
            set {
                this.idStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public rolSesion[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public Sesion sesion {
            get {
                return this.sesionField;
            }
            set {
                this.sesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UsuarioSesion usuarioSesion {
            get {
                return this.usuarioSesionField;
            }
            set {
                this.usuarioSesionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS")]
    public partial class accionSesion {
        
        private string accDescripcionField;
        
        private double accIdField;
        
        private bool accIdFieldSpecified;
        
        private double accIdAccionGrupoField;
        
        private bool accIdAccionGrupoFieldSpecified;
        
        private string accNombreField;
        
        private int accOrdenField;
        
        private bool accOrdenFieldSpecified;
        
        private string accURLField;
        
        private FiltroAccionSesion[] filtroAccionSesionField;
        
        private int nivelField;
        
        private bool nivelFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accDescripcion {
            get {
                return this.accDescripcionField;
            }
            set {
                this.accDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public double accId {
            get {
                return this.accIdField;
            }
            set {
                this.accIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accIdSpecified {
            get {
                return this.accIdFieldSpecified;
            }
            set {
                this.accIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double accIdAccionGrupo {
            get {
                return this.accIdAccionGrupoField;
            }
            set {
                this.accIdAccionGrupoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accIdAccionGrupoSpecified {
            get {
                return this.accIdAccionGrupoFieldSpecified;
            }
            set {
                this.accIdAccionGrupoFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accNombre {
            get {
                return this.accNombreField;
            }
            set {
                this.accNombreField = value;
            }
        }
        
        /// <remarks/>
        public int accOrden {
            get {
                return this.accOrdenField;
            }
            set {
                this.accOrdenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool accOrdenSpecified {
            get {
                return this.accOrdenFieldSpecified;
            }
            set {
                this.accOrdenFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string accURL {
            get {
                return this.accURLField;
            }
            set {
                this.accURLField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public FiltroAccionSesion[] filtroAccionSesion {
            get {
                return this.filtroAccionSesionField;
            }
            set {
                this.filtroAccionSesionField = value;
            }
        }
        
        /// <remarks/>
        public int nivel {
            get {
                return this.nivelField;
            }
            set {
                this.nivelField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool nivelSpecified {
            get {
                return this.nivelFieldSpecified;
            }
            set {
                this.nivelFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS")]
    public partial class FiltroAccionSesion {
        
        private string fltAplicacionesField;
        
        private string fltCatPuestoExclField;
        
        private string fltCatPuestoInclField;
        
        private string fltCctField;
        
        private string fltCctExcluidoField;
        
        private string fltClasificacionField;
        
        private string fltDelegacionesField;
        
        private string fltDescripcionField;
        
        private double fltIdAplicacionField;
        
        private bool fltIdAplicacionFieldSpecified;
        
        private string fltIdentificadorField;
        
        private string fltMunicipiosField;
        
        private string fltNivelesField;
        
        private string fltNombreField;
        
        private string fltOrigenField;
        
        private string fltSectorExclField;
        
        private string fltSectorInclField;
        
        private string fltZonaExclField;
        
        private string fltZonaInclField;
        
        private double idProcessField;
        
        private bool idProcessFieldSpecified;
        
        private double idProcessDefField;
        
        private bool idProcessDefFieldSpecified;
        
        private double idStatusField;
        
        private bool idStatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltAplicaciones {
            get {
                return this.fltAplicacionesField;
            }
            set {
                this.fltAplicacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltCatPuestoExcl {
            get {
                return this.fltCatPuestoExclField;
            }
            set {
                this.fltCatPuestoExclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltCatPuestoIncl {
            get {
                return this.fltCatPuestoInclField;
            }
            set {
                this.fltCatPuestoInclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltCct {
            get {
                return this.fltCctField;
            }
            set {
                this.fltCctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltCctExcluido {
            get {
                return this.fltCctExcluidoField;
            }
            set {
                this.fltCctExcluidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltClasificacion {
            get {
                return this.fltClasificacionField;
            }
            set {
                this.fltClasificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltDelegaciones {
            get {
                return this.fltDelegacionesField;
            }
            set {
                this.fltDelegacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltDescripcion {
            get {
                return this.fltDescripcionField;
            }
            set {
                this.fltDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public double fltIdAplicacion {
            get {
                return this.fltIdAplicacionField;
            }
            set {
                this.fltIdAplicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fltIdAplicacionSpecified {
            get {
                return this.fltIdAplicacionFieldSpecified;
            }
            set {
                this.fltIdAplicacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltIdentificador {
            get {
                return this.fltIdentificadorField;
            }
            set {
                this.fltIdentificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltMunicipios {
            get {
                return this.fltMunicipiosField;
            }
            set {
                this.fltMunicipiosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltNiveles {
            get {
                return this.fltNivelesField;
            }
            set {
                this.fltNivelesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltNombre {
            get {
                return this.fltNombreField;
            }
            set {
                this.fltNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltOrigen {
            get {
                return this.fltOrigenField;
            }
            set {
                this.fltOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltSectorExcl {
            get {
                return this.fltSectorExclField;
            }
            set {
                this.fltSectorExclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltSectorIncl {
            get {
                return this.fltSectorInclField;
            }
            set {
                this.fltSectorInclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltZonaExcl {
            get {
                return this.fltZonaExclField;
            }
            set {
                this.fltZonaExclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltZonaIncl {
            get {
                return this.fltZonaInclField;
            }
            set {
                this.fltZonaInclField = value;
            }
        }
        
        /// <remarks/>
        public double idProcess {
            get {
                return this.idProcessField;
            }
            set {
                this.idProcessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProcessSpecified {
            get {
                return this.idProcessFieldSpecified;
            }
            set {
                this.idProcessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double idProcessDef {
            get {
                return this.idProcessDefField;
            }
            set {
                this.idProcessDefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProcessDefSpecified {
            get {
                return this.idProcessDefFieldSpecified;
            }
            set {
                this.idProcessDefFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double idStatus {
            get {
                return this.idStatusField;
            }
            set {
                this.idStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idStatusSpecified {
            get {
                return this.idStatusFieldSpecified;
            }
            set {
                this.idStatusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS.datos")]
    public partial class SesionStringUsuario {
        
        private string strApeMatField;
        
        private string strApePatField;
        
        private string strLoginField;
        
        private string strMailField;
        
        private string strMenuField;
        
        private string strNombreField;
        
        private string strStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strApeMat {
            get {
                return this.strApeMatField;
            }
            set {
                this.strApeMatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strApePat {
            get {
                return this.strApePatField;
            }
            set {
                this.strApePatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strLogin {
            get {
                return this.strLoginField;
            }
            set {
                this.strLoginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strMail {
            get {
                return this.strMailField;
            }
            set {
                this.strMailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strMenu {
            get {
                return this.strMenuField;
            }
            set {
                this.strMenuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strNombre {
            get {
                return this.strNombreField;
            }
            set {
                this.strNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string strStatus {
            get {
                return this.strStatusField;
            }
            set {
                this.strStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS.datos")]
    public partial class SesionStringImpl {
        
        private string claveEstatusField;
        
        private string error_statusField;
        
        private SesionStringUsuario usuarioField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string claveEstatus {
            get {
                return this.claveEstatusField;
            }
            set {
                this.claveEstatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string error_status {
            get {
                return this.error_statusField;
            }
            set {
                this.error_statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SesionStringUsuario usuario {
            get {
                return this.usuarioField;
            }
            set {
                this.usuarioField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS.datos")]
    public partial class SesionMensajes {
        
        private int estatusField;
        
        private bool estatusFieldSpecified;
        
        private System.DateTime fechaFinField;
        
        private bool fechaFinFieldSpecified;
        
        private System.DateTime fechaIniField;
        
        private bool fechaIniFieldSpecified;
        
        private string guidField;
        
        private int idSesionField;
        
        private bool idSesionFieldSpecified;
        
        private int idUsuarioField;
        
        private bool idUsuarioFieldSpecified;
        
        private string ipField;
        
        private string mensajesField;
        
        private string menuField;
        
        /// <remarks/>
        public int estatus {
            get {
                return this.estatusField;
            }
            set {
                this.estatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool estatusSpecified {
            get {
                return this.estatusFieldSpecified;
            }
            set {
                this.estatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaFin {
            get {
                return this.fechaFinField;
            }
            set {
                this.fechaFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaFinSpecified {
            get {
                return this.fechaFinFieldSpecified;
            }
            set {
                this.fechaFinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public System.DateTime fechaIni {
            get {
                return this.fechaIniField;
            }
            set {
                this.fechaIniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fechaIniSpecified {
            get {
                return this.fechaIniFieldSpecified;
            }
            set {
                this.fechaIniFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string guid {
            get {
                return this.guidField;
            }
            set {
                this.guidField = value;
            }
        }
        
        /// <remarks/>
        public int idSesion {
            get {
                return this.idSesionField;
            }
            set {
                this.idSesionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSesionSpecified {
            get {
                return this.idSesionFieldSpecified;
            }
            set {
                this.idSesionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int idUsuario {
            get {
                return this.idUsuarioField;
            }
            set {
                this.idUsuarioField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idUsuarioSpecified {
            get {
                return this.idUsuarioFieldSpecified;
            }
            set {
                this.idUsuarioFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string ip {
            get {
                return this.ipField;
            }
            set {
                this.ipField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string mensajes {
            get {
                return this.mensajesField;
            }
            set {
                this.mensajesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string menu {
            get {
                return this.menuField;
            }
            set {
                this.menuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS.datos")]
    public partial class sesionMensajesImpl {
        
        private accionSesion[] arbolAccionesField;
        
        private int idStatusField;
        
        private bool idStatusFieldSpecified;
        
        private rolSesion[] rolesField;
        
        private SesionMensajes sesionMensajesField;
        
        private string statusField;
        
        private UsuarioSesion usuarioSesionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS")]
        public accionSesion[] arbolAcciones {
            get {
                return this.arbolAccionesField;
            }
            set {
                this.arbolAccionesField = value;
            }
        }
        
        /// <remarks/>
        public int idStatus {
            get {
                return this.idStatusField;
            }
            set {
                this.idStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idStatusSpecified {
            get {
                return this.idStatusFieldSpecified;
            }
            set {
                this.idStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS")]
        public rolSesion[] roles {
            get {
                return this.rolesField;
            }
            set {
                this.rolesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public SesionMensajes sesionMensajes {
            get {
                return this.sesionMensajesField;
            }
            set {
                this.sesionMensajesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public UsuarioSesion usuarioSesion {
            get {
                return this.usuarioSesionField;
            }
            set {
                this.usuarioSesionField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS")]
    public partial class rolSesion {
        
        private filtroRolSesion[] filtroRolSesionField;
        
        private double idProcessField;
        
        private bool idProcessFieldSpecified;
        
        private double idProcessDefField;
        
        private bool idProcessDefFieldSpecified;
        
        private double idStatusField;
        
        private bool idStatusFieldSpecified;
        
        private string rolClaveField;
        
        private string rolDescripcionField;
        
        private System.Nullable<System.DateTime> rolFechaFinField;
        
        private bool rolFechaFinFieldSpecified;
        
        private System.Nullable<System.DateTime> rolFechaIniField;
        
        private bool rolFechaIniFieldSpecified;
        
        private double rolIdAplicacionField;
        
        private bool rolIdAplicacionFieldSpecified;
        
        private string rolNombreField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(IsNullable=true)]
        public filtroRolSesion[] filtroRolSesion {
            get {
                return this.filtroRolSesionField;
            }
            set {
                this.filtroRolSesionField = value;
            }
        }
        
        /// <remarks/>
        public double idProcess {
            get {
                return this.idProcessField;
            }
            set {
                this.idProcessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProcessSpecified {
            get {
                return this.idProcessFieldSpecified;
            }
            set {
                this.idProcessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double idProcessDef {
            get {
                return this.idProcessDefField;
            }
            set {
                this.idProcessDefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProcessDefSpecified {
            get {
                return this.idProcessDefFieldSpecified;
            }
            set {
                this.idProcessDefFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double idStatus {
            get {
                return this.idStatusField;
            }
            set {
                this.idStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idStatusSpecified {
            get {
                return this.idStatusFieldSpecified;
            }
            set {
                this.idStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rolClave {
            get {
                return this.rolClaveField;
            }
            set {
                this.rolClaveField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rolDescripcion {
            get {
                return this.rolDescripcionField;
            }
            set {
                this.rolDescripcionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> rolFechaFin {
            get {
                return this.rolFechaFinField;
            }
            set {
                this.rolFechaFinField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolFechaFinSpecified {
            get {
                return this.rolFechaFinFieldSpecified;
            }
            set {
                this.rolFechaFinFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public System.Nullable<System.DateTime> rolFechaIni {
            get {
                return this.rolFechaIniField;
            }
            set {
                this.rolFechaIniField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolFechaIniSpecified {
            get {
                return this.rolFechaIniFieldSpecified;
            }
            set {
                this.rolFechaIniFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double rolIdAplicacion {
            get {
                return this.rolIdAplicacionField;
            }
            set {
                this.rolIdAplicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool rolIdAplicacionSpecified {
            get {
                return this.rolIdAplicacionFieldSpecified;
            }
            set {
                this.rolIdAplicacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string rolNombre {
            get {
                return this.rolNombreField;
            }
            set {
                this.rolNombreField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS")]
    public partial class filtroRolSesion {
        
        private string fltAplicacionesField;
        
        private string fltCatPuestoExclField;
        
        private string fltCatPuestoInclField;
        
        private string fltCctField;
        
        private string fltCctExcluidoField;
        
        private string fltClasificacionField;
        
        private string fltDelegacionesField;
        
        private string fltDescripcionField;
        
        private double fltIdAplicacionField;
        
        private bool fltIdAplicacionFieldSpecified;
        
        private string fltIdentificadorField;
        
        private string fltMunicipiosField;
        
        private string fltNivelesField;
        
        private string fltNombreField;
        
        private string fltOrigenField;
        
        private string fltSectorExclField;
        
        private string fltSectorInclField;
        
        private string fltZonaExclField;
        
        private string fltZonaInclField;
        
        private double idProcessField;
        
        private bool idProcessFieldSpecified;
        
        private double idProcessDefField;
        
        private bool idProcessDefFieldSpecified;
        
        private double idStatusField;
        
        private bool idStatusFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltAplicaciones {
            get {
                return this.fltAplicacionesField;
            }
            set {
                this.fltAplicacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltCatPuestoExcl {
            get {
                return this.fltCatPuestoExclField;
            }
            set {
                this.fltCatPuestoExclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltCatPuestoIncl {
            get {
                return this.fltCatPuestoInclField;
            }
            set {
                this.fltCatPuestoInclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltCct {
            get {
                return this.fltCctField;
            }
            set {
                this.fltCctField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltCctExcluido {
            get {
                return this.fltCctExcluidoField;
            }
            set {
                this.fltCctExcluidoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltClasificacion {
            get {
                return this.fltClasificacionField;
            }
            set {
                this.fltClasificacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltDelegaciones {
            get {
                return this.fltDelegacionesField;
            }
            set {
                this.fltDelegacionesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltDescripcion {
            get {
                return this.fltDescripcionField;
            }
            set {
                this.fltDescripcionField = value;
            }
        }
        
        /// <remarks/>
        public double fltIdAplicacion {
            get {
                return this.fltIdAplicacionField;
            }
            set {
                this.fltIdAplicacionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool fltIdAplicacionSpecified {
            get {
                return this.fltIdAplicacionFieldSpecified;
            }
            set {
                this.fltIdAplicacionFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltIdentificador {
            get {
                return this.fltIdentificadorField;
            }
            set {
                this.fltIdentificadorField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltMunicipios {
            get {
                return this.fltMunicipiosField;
            }
            set {
                this.fltMunicipiosField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltNiveles {
            get {
                return this.fltNivelesField;
            }
            set {
                this.fltNivelesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltNombre {
            get {
                return this.fltNombreField;
            }
            set {
                this.fltNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltOrigen {
            get {
                return this.fltOrigenField;
            }
            set {
                this.fltOrigenField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltSectorExcl {
            get {
                return this.fltSectorExclField;
            }
            set {
                this.fltSectorExclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltSectorIncl {
            get {
                return this.fltSectorInclField;
            }
            set {
                this.fltSectorInclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltZonaExcl {
            get {
                return this.fltZonaExclField;
            }
            set {
                this.fltZonaExclField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string fltZonaIncl {
            get {
                return this.fltZonaInclField;
            }
            set {
                this.fltZonaInclField = value;
            }
        }
        
        /// <remarks/>
        public double idProcess {
            get {
                return this.idProcessField;
            }
            set {
                this.idProcessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProcessSpecified {
            get {
                return this.idProcessFieldSpecified;
            }
            set {
                this.idProcessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double idProcessDef {
            get {
                return this.idProcessDefField;
            }
            set {
                this.idProcessDefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProcessDefSpecified {
            get {
                return this.idProcessDefFieldSpecified;
            }
            set {
                this.idProcessDefFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double idStatus {
            get {
                return this.idStatusField;
            }
            set {
                this.idStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idStatusSpecified {
            get {
                return this.idStatusFieldSpecified;
            }
            set {
                this.idStatusFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS")]
    public partial class UsuarioSesion {
        
        private double idProcessField;
        
        private bool idProcessFieldSpecified;
        
        private double idProcessDefField;
        
        private bool idProcessDefFieldSpecified;
        
        private double idStatusField;
        
        private bool idStatusFieldSpecified;
        
        private string usrApellido1Field;
        
        private string usrApellido2Field;
        
        private int usrAutenticaDAField;
        
        private bool usrAutenticaDAFieldSpecified;
        
        private int usrAutenticaLEField;
        
        private bool usrAutenticaLEFieldSpecified;
        
        private int usrAutenticaManualField;
        
        private bool usrAutenticaManualFieldSpecified;
        
        private string usrEmailField;
        
        private string usrEmployeeIdField;
        
        private double usrIdField;
        
        private bool usrIdFieldSpecified;
        
        private string usrLoginField;
        
        private string usrNombreField;
        
        private string usrURLLEField;
        
        /// <remarks/>
        public double idProcess {
            get {
                return this.idProcessField;
            }
            set {
                this.idProcessField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProcessSpecified {
            get {
                return this.idProcessFieldSpecified;
            }
            set {
                this.idProcessFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double idProcessDef {
            get {
                return this.idProcessDefField;
            }
            set {
                this.idProcessDefField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idProcessDefSpecified {
            get {
                return this.idProcessDefFieldSpecified;
            }
            set {
                this.idProcessDefFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public double idStatus {
            get {
                return this.idStatusField;
            }
            set {
                this.idStatusField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idStatusSpecified {
            get {
                return this.idStatusFieldSpecified;
            }
            set {
                this.idStatusFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usrApellido1 {
            get {
                return this.usrApellido1Field;
            }
            set {
                this.usrApellido1Field = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usrApellido2 {
            get {
                return this.usrApellido2Field;
            }
            set {
                this.usrApellido2Field = value;
            }
        }
        
        /// <remarks/>
        public int usrAutenticaDA {
            get {
                return this.usrAutenticaDAField;
            }
            set {
                this.usrAutenticaDAField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usrAutenticaDASpecified {
            get {
                return this.usrAutenticaDAFieldSpecified;
            }
            set {
                this.usrAutenticaDAFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int usrAutenticaLE {
            get {
                return this.usrAutenticaLEField;
            }
            set {
                this.usrAutenticaLEField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usrAutenticaLESpecified {
            get {
                return this.usrAutenticaLEFieldSpecified;
            }
            set {
                this.usrAutenticaLEFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        public int usrAutenticaManual {
            get {
                return this.usrAutenticaManualField;
            }
            set {
                this.usrAutenticaManualField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usrAutenticaManualSpecified {
            get {
                return this.usrAutenticaManualFieldSpecified;
            }
            set {
                this.usrAutenticaManualFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usrEmail {
            get {
                return this.usrEmailField;
            }
            set {
                this.usrEmailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usrEmployeeId {
            get {
                return this.usrEmployeeIdField;
            }
            set {
                this.usrEmployeeIdField = value;
            }
        }
        
        /// <remarks/>
        public double usrId {
            get {
                return this.usrIdField;
            }
            set {
                this.usrIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool usrIdSpecified {
            get {
                return this.usrIdFieldSpecified;
            }
            set {
                this.usrIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usrLogin {
            get {
                return this.usrLoginField;
            }
            set {
                this.usrLoginField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usrNombre {
            get {
                return this.usrNombreField;
            }
            set {
                this.usrNombreField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(IsNullable=true)]
        public string usrURLLE {
            get {
                return this.usrURLLEField;
            }
            set {
                this.usrURLLEField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.7.3056.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://schemas.datacontract.org/2004/07/SCS")]
    public partial class Sesion {
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getSesionCompletedEventHandler(object sender, getSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SesionImpl Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SesionImpl)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getSesionDinamicaCompletedEventHandler(object sender, getSesionDinamicaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSesionDinamicaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSesionDinamicaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public sesionMensajesImpl Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((sesionMensajesImpl)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getCerrarSesionCompletedEventHandler(object sender, getCerrarSesionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getCerrarSesionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getCerrarSesionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SesionImpl Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SesionImpl)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    public delegate void getSesionStringCompletedEventHandler(object sender, getSesionStringCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.7.3056.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getSesionStringCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getSesionStringCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public SesionStringImpl Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((SesionStringImpl)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591