//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiciosWeb.EnvioCorreo {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfSalida", Namespace="http://seg.guanajuato.gob.mx.ws.Correo/", ItemName="salida")]
    [System.SerializableAttribute()]
    public class ArrayOfSalida : System.Collections.Generic.List<ServiciosWeb.EnvioCorreo.salida> {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="salida", Namespace="http://seg.guanajuato.gob.mx.ws.Correo/")]
    [System.SerializableAttribute()]
    public partial class salida : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int claveEstatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string estatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string extensionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int claveEstatus {
            get {
                return this.claveEstatusField;
            }
            set {
                if ((this.claveEstatusField.Equals(value) != true)) {
                    this.claveEstatusField = value;
                    this.RaisePropertyChanged("claveEstatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string estatus {
            get {
                return this.estatusField;
            }
            set {
                if ((object.ReferenceEquals(this.estatusField, value) != true)) {
                    this.estatusField = value;
                    this.RaisePropertyChanged("estatus");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string extension {
            get {
                return this.extensionField;
            }
            set {
                if ((object.ReferenceEquals(this.extensionField, value) != true)) {
                    this.extensionField = value;
                    this.RaisePropertyChanged("extension");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://seg.guanajuato.gob.mx.ws.Correo/", ConfigurationName="EnvioCorreo.WSCorreoSoap")]
    public interface WSCorreoSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Destinatario del espacio de nombres http://seg.guanajuato.gob.mx.ws.Correo/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://seg.guanajuato.gob.mx.ws.Correo/Enviarcorreo", ReplyAction="*")]
        ServiciosWeb.EnvioCorreo.EnviarcorreoResponse Enviarcorreo(ServiciosWeb.EnvioCorreo.EnviarcorreoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://seg.guanajuato.gob.mx.ws.Correo/Enviarcorreo", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiciosWeb.EnvioCorreo.EnviarcorreoResponse> EnviarcorreoAsync(ServiciosWeb.EnvioCorreo.EnviarcorreoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarcorreoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Enviarcorreo", Namespace="http://seg.guanajuato.gob.mx.ws.Correo/", Order=0)]
        public ServiciosWeb.EnvioCorreo.EnviarcorreoRequestBody Body;
        
        public EnviarcorreoRequest() {
        }
        
        public EnviarcorreoRequest(ServiciosWeb.EnvioCorreo.EnviarcorreoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://seg.guanajuato.gob.mx.ws.Correo/")]
    public partial class EnviarcorreoRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string Destinatario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string CC;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Asunto;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string Cuerpo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string Ruta;
        //Edicion Sep23
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue = false, Order = 5)]
        public string Elemento;


        public EnviarcorreoRequestBody() {
        }
        
        public EnviarcorreoRequestBody(string Destinatario, string CC, string Asunto, string Cuerpo, string Ruta, string Elemento) {
            this.Destinatario = Destinatario;
            this.CC = CC;
            this.Asunto = Asunto;
            this.Cuerpo = Cuerpo;
            this.Ruta = Ruta;
            this.Elemento = Elemento;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EnviarcorreoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EnviarcorreoResponse", Namespace="http://seg.guanajuato.gob.mx.ws.Correo/", Order=0)]
        public ServiciosWeb.EnvioCorreo.EnviarcorreoResponseBody Body;
        
        public EnviarcorreoResponse() {
        }
        
        public EnviarcorreoResponse(ServiciosWeb.EnvioCorreo.EnviarcorreoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://seg.guanajuato.gob.mx.ws.Correo/")]
    public partial class EnviarcorreoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ServiciosWeb.EnvioCorreo.ArrayOfSalida EnviarcorreoResult;
        
        public EnviarcorreoResponseBody() {
        }
        
        public EnviarcorreoResponseBody(ServiciosWeb.EnvioCorreo.ArrayOfSalida EnviarcorreoResult) {
            this.EnviarcorreoResult = EnviarcorreoResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WSCorreoSoapChannel : ServiciosWeb.EnvioCorreo.WSCorreoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WSCorreoSoapClient : System.ServiceModel.ClientBase<ServiciosWeb.EnvioCorreo.WSCorreoSoap>, ServiciosWeb.EnvioCorreo.WSCorreoSoap {
        
        public WSCorreoSoapClient() {
        }
        
        public WSCorreoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WSCorreoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCorreoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WSCorreoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ServiciosWeb.EnvioCorreo.EnviarcorreoResponse ServiciosWeb.EnvioCorreo.WSCorreoSoap.Enviarcorreo(ServiciosWeb.EnvioCorreo.EnviarcorreoRequest request) {
            return base.Channel.Enviarcorreo(request);
        }
        
        public ServiciosWeb.EnvioCorreo.ArrayOfSalida Enviarcorreo(string Destinatario, string CC, string Asunto, string Cuerpo, string Ruta, string Elemento) {
            ServiciosWeb.EnvioCorreo.EnviarcorreoRequest inValue = new ServiciosWeb.EnvioCorreo.EnviarcorreoRequest();
            inValue.Body = new ServiciosWeb.EnvioCorreo.EnviarcorreoRequestBody();
            inValue.Body.Destinatario = Destinatario;
            inValue.Body.CC = CC;
            inValue.Body.Asunto = Asunto;
            inValue.Body.Cuerpo = Cuerpo;
            inValue.Body.Ruta = Ruta;
            inValue.Body.Elemento = Elemento;
            ServiciosWeb.EnvioCorreo.EnviarcorreoResponse retVal = ((ServiciosWeb.EnvioCorreo.WSCorreoSoap)(this)).Enviarcorreo(inValue);
            return retVal.Body.EnviarcorreoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiciosWeb.EnvioCorreo.EnviarcorreoResponse> ServiciosWeb.EnvioCorreo.WSCorreoSoap.EnviarcorreoAsync(ServiciosWeb.EnvioCorreo.EnviarcorreoRequest request) {
            return base.Channel.EnviarcorreoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiciosWeb.EnvioCorreo.EnviarcorreoResponse> EnviarcorreoAsync(string Destinatario, string CC, string Asunto, string Cuerpo, string Ruta) {
            ServiciosWeb.EnvioCorreo.EnviarcorreoRequest inValue = new ServiciosWeb.EnvioCorreo.EnviarcorreoRequest();
            inValue.Body = new ServiciosWeb.EnvioCorreo.EnviarcorreoRequestBody();
            inValue.Body.Destinatario = Destinatario;
            inValue.Body.CC = CC;
            inValue.Body.Asunto = Asunto;
            inValue.Body.Cuerpo = Cuerpo;
            inValue.Body.Ruta = Ruta;
            return ((ServiciosWeb.EnvioCorreo.WSCorreoSoap)(this)).EnviarcorreoAsync(inValue);
        }
    }
}
